name: Backend Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Copy config file
        working-directory: backend/config
        run: cp config.env.example config.env      

      - name: Inject dynamic MONGO_URI
        working-directory: backend/config
        run: |
          echo "Github MONGO_URI=${{ secrets.MONGO_URI }}"  
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> config.env  

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run Project
        working-directory: backend
        run: npm run dev

      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t backend:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name backend-container backend:latest
